package simpledb;

import java.util.*;
import java.io.*;
import java.math.*;

/**
 * Each instance of HeapPage stores data for one page of HeapFiles and 
 * implements the Page interface that is used by BufferPool.
 *
 * @see HeapFile
 * @see BufferPool
 *
 */
public class HeapPage implements Page {

    HeapPageId pid;
    TupleDesc td;
    byte header[];
    Tuple tuples[];
    int numSlots;
    TransactionId tid;
    byte[] oldData;
    boolean dirty;

    /**
     * Create a HeapPage from a set of bytes of data read from disk.
     * The format of a HeapPage is a set of header bytes indicating
     * the slots of the page that are in use, some number of tuple slots.
     *  Specifically, the number of tuples is equal to: <p>
     *          floor((BufferPool.PAGE_SIZE*8) / (tuple size * 8 + 1))
     * <p> where tuple size is the size of tuples in this
     * database table, which can be determined via {@link Catalog#getTupleDesc}.
     * The number of 8-bit header words is equal to:
     * <p>
     *      ceiling(no. tuple slots / 8)
     * <p>
     * @see Database#getCatalog
     * @see Catalog#getTupleDesc
     * @see BufferPool#PAGE_SIZE
     */
    public HeapPage(HeapPageId id, byte[] data) throws IOException {
        this.pid = id;
        this.td = Database.getCatalog().getTupleDesc(id.getTableId());
        this.numSlots = getNumTuples();
        DataInputStream dis = new DataInputStream(
                new ByteArrayInputStream(data));

        // allocate and read the header slots of this page
        header = new byte[getHeaderSize()];
        for (int i = 0; i < header.length; i++)
            header[i] = dis.readByte();

        try {
            // allocate and read the actual records of this page
            tuples = new Tuple[numSlots];
            for (int i = 0; i < tuples.length; i++)
                try
            {
                tuples[i] = readNextTuple(dis, i);
            }catch (NoSuchElementException ee)
            {
                tuples[i]=null;
            }
        } catch (NoSuchElementException e) {
            e.printStackTrace();
        }
        dis.close();

        setBeforeImage();
    }

    /** Retrieve the number of tuples on this page.
        @return the number of tuples on this page
    */
    private int getNumTuples() {        
        // some code goes here
        int tupsPerPage= (int)Math.floor((BufferPool.PAGE_SIZE*8)/(td.getSize()*8+1));
        return tupsPerPage;

    }

    /**
     * Computes the number of bytes in the header of a page in a HeapFile with each tuple occupying tupleSize bytes
     * @return the number of bytes in the header of a page in a HeapFile with each tuple occupying tupleSize bytes
     */
    private int getHeaderSize() {   
        // some code goes here
        return (int) Math.ceil(this.numSlots/8.0);
                 
    }
    
    /** Return a view of this page before it was modified
        -- used by recovery */
    public HeapPage getBeforeImage(){
        try {
            return new HeapPage(pid,oldData);
        } catch (IOException e) {
            e.printStackTrace();
            //should never happen -- we parsed it OK before!
            System.exit(1);
        }
        return null;
    }
    
    public void setBeforeImage() {
        oldData = getPageData().clone();
    }

    /**
     * @return the PageId associated with this page.
     */
    public HeapPageId getId() {
    // some code goes here
        return pid;
    }

    /**
     * Suck up tuples from the source file.
     */
    private Tuple readNextTuple(DataInputStream dis, int slotId)
            throws NoSuchElementException {
        // if associated bit is not set, read forward to the next tuple, and
        // return null.
        if (!isSlotUsed(slotId)) {
            try {
                dis.skip(td.getSize() * slotId);
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            throw new NoSuchElementException();
        }

        // read fields in the tuple
        Tuple t = new Tuple(td);
        RecordId rid = new RecordId(pid, slotId);
        t.setRecordId(rid);
        try {
            for (int j=0; j<td.numFields(); j++) {
                Field f = td.getFieldType(j).parse(dis);
                t.setField(j, f);
            }
        } catch (java.text.ParseException e) {
            e.printStackTrace();
            throw new NoSuchElementException("parsing error!");
        }

        return t;
    }

    /**
     * Generates a byte array representing the contents of this page.
     * Used to serialize this page to disk.
     * <p>
     * The invariant here is that it should be possible to pass the byte
     * array generated by getPageData to the HeapPage constructor and
     * have it produce an identical HeapPage object.
     *
     * @see #HeapPage
     * @return A byte array correspond to the bytes of this page.
     */
    public byte[] getPageData() {
        int len = BufferPool.PAGE_SIZE;
        ByteArrayOutputStream baos = new ByteArrayOutputStream(len);
        DataOutputStream dos = new DataOutputStream(baos);

        // create the header of the page

        for (int i=0; i<header.length; i++) {
            try {
                dos.writeByte(header[i]);
            } catch (IOException e) {
                // this really shouldn't happen
                e.printStackTrace();
            }
        }

        // create the tuples
        for (int i=0; i<tuples.length; i++) {

            // empty slot
            if (!isSlotUsed(i)) {
                for (int j=0; j<td.getSize(); j++) {
                    try {
                        dos.writeByte(0);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                }
                continue;
            }

            // non-empty slot
            for (int j=0; j<td.numFields(); j++) {
                Field f = tuples[i].getField(j);
                try {
                    f.serialize(dos);
                
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

        // padding
        int zerolen = BufferPool.PAGE_SIZE - (header.length + td.getSize() * tuples.length); //- numSlots * td.getSize();
        byte[] zeroes = new byte[zerolen];
        try {
            dos.write(zeroes, 0, zerolen);
        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            dos.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return baos.toByteArray();
    }

    /**
     * Static method to generate a byte array corresponding to an empty
     * HeapPage.
     * Used to add new, empty pages to the file. Passing the results of
     * this method to the HeapPage constructor will create a HeapPage with
     * no valid tuples in it.
     *
     * @return The returned ByteArray.
     */
    public static byte[] createEmptyPageData() {
        int len = BufferPool.PAGE_SIZE;
        return new byte[len]; //all 0
    }

    /**
     * Delete the specified tuple from the page;  the tuple should be updated to reflect
     *   that it is no longer stored on any page.
     * @throws DbException if this tuple is not on this page, or tuple slot is
     *         already empty.
     * @param t The tuple to delete
     */
    public void deleteTuple(Tuple t) throws DbException {
        // some code goes here
        // not necessary for lab1
        RecordId rid = t.getRecordId();
        int i=rid.tupleno();

        if (rid.getPageId() != pid) {
            throw new DbException("this tuple is not on this page");
        }
        if (!isSlotUsed(i)){
            throw new DbException("tuple slot is already empty");
        }
        tuples[i]=null;
        markSlotUsed(i, false);
    }

    /**
     * Adds the specified tuple to the page;  the tuple should be updated to reflect
     *  that it is now stored on this page.
     * @throws DbException if the page is full (no empty slots) or tupledesc
     *         is mismatch.
     * @param t The tuple to add.
     */
    public void insertTuple(Tuple t) throws DbException {
        // some code goes here
        // not necessary for lab1
        if (this.getNumEmptySlots()==0){
            throw new DbException("page is full");
        }
        if (!t.getTupleDesc().equals(this.td)){
            throw new DbException("TupleDesc is mismatch");
        }
        int i= this.nextEmptySlotNum();
        tuples[i]=t;
        markSlotUsed(i, true);
        RecordId rid=new RecordId(pid,i);
        t.setRecordId(rid);

    }
    public int nextEmptySlotNum() throws DbException{
        for (int i=0;i<header.length*8;i++){
            if (!isSlotUsed(i))
                return i;
        }
        throw new DbException("no nextEmptySlotNum available");

    }

    /**
     * Marks this page as dirty/not dirty and record that transaction
     * that did the dirtying
     */
    public void markDirty(boolean dirty, TransactionId tid) {
        // some code goes here
        // not necessary for lab1
        this.dirty = dirty;
        if (dirty){
            this.tid=tid;
        }
        else{
            this.tid=null;
        }
    }

    /**
     * Returns the tid of the transaction that last dirtied this page, or null if the page is not dirty
     */
    public TransactionId isDirty() {
        // some code goes here
    // Not necessary for lab1
        return tid;   
    }

    /**
     * Returns the number of empty slots on this page.
     */
    public int getNumEmptySlots() {
        // some code goes here
        int emptyslots = 0;
        for (int i=0;i<numSlots;i++){
            if (!(this.isSlotUsed(i))){
                emptyslots++;
            }
        }
        return emptyslots;
    }

    /**
     * Returns true if associated slot on this page is filled.
     */
    public boolean isSlotUsed(int i) throws IllegalArgumentException{
        // some code goes here
        if (i < 0 || i > numSlots) {
            throw new IllegalArgumentException("Invalid slot number"); 
        }
            //say i=65, it's in the header[8],first bit, so [0]
            int whichByte = i / 8;
            int whichBit = i % 8;
            if (whichByte>=header.length){
                throw new IllegalArgumentException("Invalid whichByte");
            }
            //use byteArray to represent the byte representing ith slot
            byte[] byteArContainsI = new byte[] {header[whichByte]};
            //convert the bytearray into BigInteger
            BigInteger bi = new BigInteger(byteArContainsI);
            //test if the conrresponsing bit in the BigInteger is 1.
            boolean biused;
            biused=bi.testBit(whichBit);
            return biused;
    }

    /**
     * Abstraction to fill or clear a slot on this page.
     */
    private void markSlotUsed(int i, boolean value) {
        // some code goes here
        // not necessary for lab1
        int whichByte = i / 8;
        int whichBit = i % 8;
        byte[] byteArContainsI = new byte[] {header[whichByte]};
        BigInteger bi = new BigInteger(byteArContainsI);
        if (value) {
            bi=bi.setBit(whichBit);
        } else{
            bi=bi.clearBit(whichBit);
        }
        byte [] changedbyteArContainsI = bi.toByteArray();
        byte changedByte=changedbyteArContainsI[changedbyteArContainsI.length-1];
        header[whichByte]=changedByte;

    }

    /**
     * @return an iterator over all tuples on this page (calling remove on this iterator throws an UnsupportedOperationException)
     * (note that this iterator shouldn't return tuples in empty slots!)
     */
    public Iterator<Tuple> iterator() {
        // some code goes here
        ArrayList<Tuple> tuplesInUse = new ArrayList<Tuple>();
        for (int i=0;i<tuples.length;i++){
            if (isSlotUsed(i)){
                tuplesInUse.add(tuples[i]);
            }
        }
        return new HeapPageIterator<Tuple>(tuplesInUse);
    }

}

